name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Make the program
      run: make
      
    - name: Test
      run: ./aasm SCR_scripts/test.aa -e
      
    - name: pwd
      run: pwd
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: ./*
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error
